### ISSUE TITLE
directory_tree (LoadError)

### ISSUE THREAD

**Issue by oshanz** [os6sense/xumlidot#22]
* gem install specific_install
* gem specific_install https://github.com/os6sense/xumlidot.git
```
[sisc@fedora rlws]$ xumlidot app
Traceback (most recent call last):
	5: from /home/sisc/.asdf/installs/ruby/2.6.6/bin/xumlidot:23:in `<main>'
	4: from /home/sisc/.asdf/installs/ruby/2.6.6/bin/xumlidot:23:in `load'
	3: from /home/sisc/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/xumlidot-1.0.0.pre/bin/xumlidot:3:in `<top (required)>'
	2: from /home/sisc/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/xumlidot-1.0.0.pre/bin/xumlidot:3:in `require_relative'
	1: from /home/sisc/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/xumlidot-1.0.0.pre/lib/xumlidot.rb:3:in `<top (required)>'
/home/sisc/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/xumlidot-1.0.0.pre/lib/xumlidot.rb:3:in `require_relative': cannot load such file -- /home/sisc/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/xumlidot-1.0.0.pre/lib/xumlidot/directory_tree (LoadError)
````

**Comment by os6sense** [comment]
@oshanz Sorry it took me so long to get around to this. xumlidot is now published on Rubygems so you can just use `gem install xumlidot`
